// src/components/copyrights.vue
<template>
  <div class="text-gray-300 xl:text-gray-700 text-sm flex items-center">
    <span>{{
      isPolish ? 'wszystkie prawa zastrzeżone' : 'all rights reserved'
    }}</span>
    <i class="px-2 far fa-copyright"></i>
    <span>{{ year }}</span>
  </div>
</template>

<script>
export default {
  name: 'SmCopyrights',
  computed: {
    year: function () {
      return new Date().getFullYear()
    },
    isPolish: function () {
      return this.$store.getters['settings/isPolish']
    },
  },
}
</script>

// src/components/shared/Copyrights.svelte
<script>
	import { isPolish, isEnglish, toggle } from '../../stores/language';

	const year = new Date().getFullYear();
</script>

<div class="text-gray-300 xl:text-gray-700 text-sm flex items-center font-work">
	<span>{$isPolish ? 'wszystkie prawa zastrzeżone' : 'all rights reserved'}</span>
	<i class="px-2 far fa-copyright" />
	<span>{year}</span>
</div>
