// src/components/content/maciej/skillset/Design.svelte
<script>
	import Percenter from './../../../shared/Percenter.svelte';
</script>

<div>
	<Percenter value={0.2}>Two parts design</Percenter>

	<section class="pt-4 font-work text-gray-400">
		<section class="pb-4 text-sm">
			<div class="text-gray-200 text-xs">Aesthethic sense</div>
			<div>Extending and creating simple graphics ... minimalist ...</div>
		</section>

		<section class="pb-4 text-sm">
			<div class="text-gray-200 text-xs">User experience</div>
			<div>Application journey ...</div>
		</section>

		<section class="pb-4 text-sm">
			<div class="text-gray-200 text-xs">Solution</div>
			<div>Often the best answer is to redesign ...</div>
		</section>
	</section>
</div>

// src/components/content/maciej/skillset/design.vue
<template>
  <div>
    <shared-percenter :value="0.2">Two parts design</shared-percenter>

    <section class="pt-4 font-work text-gray-400">
      <section class="pb-4 text-sm">
        <div class="text-gray-200 text-xs">Aesthethic sense</div>
        <div>Extending and creating simple graphics ... minimalist ...</div>
      </section>

      <section class="pb-4 text-sm">
        <div class="text-gray-200 text-xs">User experience</div>
        <div>Application journey ...</div>
      </section>

      <section class="pb-4 text-sm">
        <div class="text-gray-200 text-xs">Solution</div>
        <div>Often the best answer is to redesign ...</div>
      </section>
    </section>
  </div>
</template>

<script>
export default {
  name: 'SmContentMaciejSkillsetDesign',
}
</script>
