// src/components/content/maciej/skillset/engineering.vue
<template>
  <div>
    <shared-percenter :value="0.5">Five parts engineering</shared-percenter>

    <section class="pt-4 font-work text-gray-400">
      <section class="pb-4 text-sm">
        <div class="text-gray-200 text-xs">Programming languages</div>
        <div>
          Frequent exposure to both vanilla and modern
          <span class="text-gray-700">Javascript</span>,
          <span class="text-gray-700">Typescript</span> and
          <span class="text-gray-700">Coffeescript</span>.
        </div>
        <div>
          Brief experience of .NET technologies, Java and a few other languages.
        </div>
      </section>

      <section class="pb-4 text-sm">
        <div class="text-gray-200 text-xs">Front-end stack</div>
        <div>
          Strong understanding of
          <span class="text-gray-700">React</span>,
          <span class="text-gray-700">Vue</span> and good old
          <span class="text-gray-700">AngularJS</span>.
        </div>

        <div>
          Past experience with KnockoutJS, Ember, BackboneJS or even things like
          <a href="https://github.com/quirkey/sammy" target="_blank">sammyJS</a
          >.
        </div>
        <div class="text-gray-700">
          Ability to work outside of mainstream tools, frameworks and libraries.
        </div>
        <div class="pt-4">
          Understanding of uni-directional data flow tools such as
          <span class="text-gray-700">Redux</span> or
          <span class="text-gray-700">Vuex</span>.
        </div>
        <div>
          Proficiency in leveraging event-driven applications and more
          traditional MVC or MVVM frameworks.
        </div>
        <div class="pt-4">
          Capacity to work on the build level with tools like
          <span class="text-gray-700">webpack</span>,
          <span class="text-gray-700">gulp</span>,
          <span class="text-gray-700">grunt</span> and even
          <span class="text-gray-700">bower</span>.
        </div>
        <div>
          Understanding of modern front-end environment of
          <span class="text-gray-700">NodeJS</span> and
          <span class="text-gray-700">NPM</span>.
        </div>
      </section>

      <section class="pb-4 text-sm">
        <div class="text-gray-200 text-xs">Architecture</div>
        <div>
          I build robust products by
          <span class="text-gray-700">clean coding</span>, following
          <span class="text-gray-700">12-factor app</span> methodology,
          <span class="text-gray-700">TDD</span> and others.
        </div>
        <!-- <div>
          <span class="text-gray-700">SOAP</span>,
          <span class="text-gray-700">REST</span> and
          <span class="text-gray-700">SPA</span> are not afterhours phrases for
          me.
        </div> -->
        <div class="pt-4">
          Delivery of user interfaces is my craft, but creation of modern UI is
          a demanding process - therefore I can operate unix based systems,
          create and modify CI/CD process, configure and setup cloud
          environments that will host the application, integrate 3rd party tools
          and more.
        </div>
      </section>
    </section>
  </div>
</template>

<script>
export default {
  name: 'ContentMaciejSkillsetEngineering',
}
</script>

// src/components/content/maciej/skillset/Engineering.svelte
<script>
	import Percenter from './../../../shared/Percenter.svelte';
</script>

<div>
	<Percenter value={0.5}>Five parts engineering</Percenter>

	<section class="pt-4 font-work text-gray-400">
		<section class="pb-4 text-sm">
			<div class="text-gray-200 text-xs">Programming languages</div>
			<div>
				Frequent exposure to both vanilla and modern
				<span class="text-gray-700">Javascript</span>,
				<span class="text-gray-700">Typescript</span> and
				<span class="text-gray-700">Coffeescript</span>.
			</div>
			<div>Brief experience of .NET technologies, Java and a few other languages.</div>
		</section>

		<section class="pb-4 text-sm">
			<div class="text-gray-200 text-xs">Front-end stack</div>
			<div>
				Strong understanding of
				<span class="text-gray-700">React</span>,
				<span class="text-gray-700">Vue</span> and good old
				<span class="text-gray-700">AngularJS</span>.
			</div>

			<div>
				Past experience with KnockoutJS, Ember, BackboneJS or even things like
				<a href="https://github.com/quirkey/sammy" target="_blank">sammyJS</a>.
			</div>
			<div class="text-gray-700">
				Ability to work outside of mainstream tools, frameworks and libraries.
			</div>
			<div class="pt-4">
				Understanding of uni-directional data flow tools such as
				<span class="text-gray-700">Redux</span> or
				<span class="text-gray-700">Vuex</span>.
			</div>
			<div>
				Proficiency in leveraging event-driven applications and more traditional MVC or MVVM
				frameworks.
			</div>
			<div class="pt-4">
				Capacity to work on the build level with tools like
				<span class="text-gray-700">webpack</span>,
				<span class="text-gray-700">gulp</span>,
				<span class="text-gray-700">grunt</span> and even
				<span class="text-gray-700">bower</span>.
			</div>
			<div>
				Understanding of modern front-end environment of
				<span class="text-gray-700">NodeJS</span> and
				<span class="text-gray-700">NPM</span>.
			</div>
		</section>

		<section class="pb-4 text-sm">
			<div class="text-gray-200 text-xs">Architecture</div>
			<div>
				I build robust products by
				<span class="text-gray-700">clean coding</span>, following
				<span class="text-gray-700">12-factor app</span> methodology,
				<span class="text-gray-700">TDD</span> and others.
			</div>
			<!-- <div>
          <span class="text-gray-700">SOAP</span>,
          <span class="text-gray-700">REST</span> and
          <span class="text-gray-700">SPA</span> are not afterhours phrases for
          me.
        </div> -->
			<div class="pt-4">
				Delivery of user interfaces is my craft, but creation of modern UI is a demanding process -
				therefore I can operate unix based systems, create and modify CI/CD process, configure and
				setup cloud environments that will host the application, integrate 3rd party tools and more.
			</div>
		</section>
	</section>
</div>
