// src/components/content/maciej/skillset/management.vue
<template>
  <div>
    <shared-percenter :value="0.3">Three parts organisation</shared-percenter>

    <section class="pt-4 font-work text-gray-400">
      <section class="pb-4 text-sm">
        <div class="text-gray-200 text-xs">Personal awareness</div>
        <div>
          Determination and focus can get you a long way, but to achieve truly
          great things you need an
          <span class="text-gray-700">objective</span> and a
          <span class="text-gray-700">coordinated effort</span>.
        </div>

        <div class="pt-4">
          In my work I apply objective
          <span class="text-gray-700">breakdown</span>,
          <span class="text-gray-700">planning</span> and
          <span class="text-gray-700">reviews</span> to ensure progress towards
          our intended target. Keeping
          <span class="text-gray-700">flexibility</span> while staying on the
          way to the end-goal.
        </div>
      </section>

      <section class="pb-4 text-sm">
        <div class="text-gray-200 text-xs">Agile</div>
        <div>Many techniques ...</div>
      </section>

      <section class="pb-4 text-sm">
        <div class="text-gray-200 text-xs">Teamwork</div>
        <div>Many techniques ...</div>
        <div class="pt-4">
          I can <span class="text-gray-700">lead</span>, but I can also
          <span class="text-gray-700">follow</span>.
        </div>
      </section>
    </section>
  </div>
</template>

<script>
export default {
  name: 'SmContentMaciejSkillsetManagement',
}
</script>

// src/components/content/maciej/skillset/Management.svelte
<script>
	import Percenter from './../../../shared/Percenter.svelte';
</script>

<div>
	<Percenter value={0.3}>Three parts organisation</Percenter>

	<section class="pt-4 font-work text-gray-400">
		<section class="pb-4 text-sm">
			<div class="text-gray-200 text-xs">Personal awareness</div>
			<div>
				Determination and focus can get you a long way, but to achieve truly great things you need
				an
				<span class="text-gray-700">objective</span> and a
				<span class="text-gray-700">coordinated effort</span>.
			</div>

			<div class="pt-4">
				In my work I apply objective
				<span class="text-gray-700">breakdown</span>,
				<span class="text-gray-700">planning</span> and
				<span class="text-gray-700">reviews</span> to ensure progress towards our intended target.
				Keeping
				<span class="text-gray-700">flexibility</span> while staying on the way to the end-goal.
			</div>
		</section>

		<section class="pb-4 text-sm">
			<div class="text-gray-200 text-xs">Agile</div>
			<div>Many techniques ...</div>
		</section>

		<section class="pb-4 text-sm">
			<div class="text-gray-200 text-xs">Teamwork</div>
			<div>Many techniques ...</div>
			<div class="pt-4">
				I can <span class="text-gray-700">lead</span>, but I can also
				<span class="text-gray-700">follow</span>.
			</div>
		</section>
	</section>
</div>
